version: "3"

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    environment:
      - WAIT_HOSTS=mongo
    ports:
      - "8080:8080"
    volumes:
      - ./back-end:/app/back-end # Volume pour le backend

  front-vue:
    build:
      context: ./front-vue
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front-vue:/app/front-vue # Volume pour le front-end
      - /app/node_modules
