version: "3"
services:
  backend:
    build:
      context: ./back-end-golang
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    environment:
      - WAIT_HOSTS=mongo
    ports:
      - "8080:8080"
    volumes:
      - ./back-end:/app/back-end  # Exemple de volume pour le backend

  front-end:
    build:
      context: ./front-vue
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - /front-vue:/app/front-vue  # Volume pour le front-end
