# Étape 1 : Utilisez une image Node.js pour construire l'application Vue.js
FROM node:18 as build

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez package.json et package-lock.json dans le conteneur
COPY package*.json ./

# Installez les dépendances du projet
RUN npm ci

# Copiez tous les fichiers du projet dans le conteneur
COPY . .

# Compilez l'application Vue.js pour la production
RUN npm run build

# Exposez le port 3000 pour accéder à l'application via le navigateur
EXPOSE 3000
